export const FORM_DATA_REQUIEST = 'FORM_DATA_REQUIEST';
export const FORM_DATA_SUCCESS = 'FORM_DATA_SUCCESS';
export const FORM_DATA_FAILED = 'FORM_DATA_FAILED';
export const FORM_DATA_IMAGE = 'FORM_DATA_IMAGE';
export const FORM_DATA_IMAGE_SUCCESS = 'FORM_DATA_IMAGE_SUCCESS';
